name: Build

on:
  push:
    branches: [ gh-actions-builds ]

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fortran compiler, OpenGL/X dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran cmake libglu1-mesa-dev xorg-dev

      - name: Configure
        run: cmake -B build -S source -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build
        
  build-macos-intel:
    name: Build (macOS Intel)
    runs-on: macos-15-intel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install gfortran

      - name: Set Fortran compiler for cmake
        run: echo "FC=$(brew --prefix)/bin/gfortran" >> $GITHUB_ENV
        
      - name: Configure
        run: cmake -B build -S source -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build
