name: Build

on:
  push:
    branches: [ gh-actions-builds ]

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fortran compiler, OpenGL/X dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran cmake libglu1-mesa-dev xorg-dev

      - name: Configure
        run: cmake -B build -S source -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Bundle Linux dependencies
        run: |
          cp build/libscigma.so scigma/

          ldd build/libscigma.so \
          | awk '/=>/ { print $3 }' \
          | grep -vE 'libc\.so|libm\.so|ld-linux' \
          | xargs -I{} cp {} scigma/
 
          patchelf --set-rpath '$ORIGIN' scigma/libscigma.so

  build-macos-intel:
    name: Build (macOS Intel)
    runs-on: macos-15-intel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install gfortran
          
      - name: Expose Homebrew Fortran compiler
        run: |
          echo "$(brew --prefix gcc)/bin" >> $GITHUB_PATH
          echo "FC=gfortran" >> $GITHUB_ENV

      - name: Configure
        run: cmake -B build -S source -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wno-error=poison-system-directories -Wno-covered-switch-default"

      - name: Build
        run: cmake --build build

      - name: Bundle macOS dependencies
        run: |
          cp build/libscigma.dylib scigma/

          otool -L build/libscigma.dylib \
          | tail -n +2 \
          | awk '{print $1}' \
          | grep -v '^/usr/lib/' \
          | grep -v '^/System/' \
          | xargs -I{} cp {} scigma/

          install_name_tool -add_rpath @loader_path scigma/libscigma.dylib

          for lib in scigma/*.dylib; do
            install_name_tool -id "@loader_path/$(basename "$lib")" "$lib"
            install_name_tool -change "$(otool -L scigma/libscigma.dylib | grep $(basename "$lib") | awk '{print $1}')" \
            "@loader_path/$(basename "$lib")" scigma/libscigma.dylib || true
          done

  build-macos-arm:
    name: Build (macOS ARM)
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install gfortran
          
      - name: Expose Homebrew Fortran compiler
        run: |
          echo "$(brew --prefix gcc)/bin" >> $GITHUB_PATH
          echo "FC=gfortran" >> $GITHUB_ENV

      - name: Disable libpng NEON on ARM
        run: |
          echo "CFLAGS=-DPNG_ARM_NEON_OPT=0" >> $GITHUB_ENV
          echo "CPPFLAGS=-DPNG_ARM_NEON_OPT=0" >> $GITHUB_ENV

      - name: Configure
        run: cmake -B build -S source -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wno-error=poison-system-directories -Wno-covered-switch-default"

      - name: Build
        run: cmake --build build

      - name: Bundle macOS dependencies
        run: |
          cp build/libscigma.dylib scigma/

          otool -L build/libscigma.dylib \
          | tail -n +2 \
          | awk '{print $1}' \
          | grep -v '^/usr/lib/' \
          | grep -v '^/System/' \
          | xargs -I{} cp {} scigma/

          install_name_tool -add_rpath @loader_path scigma/libscigma.dylib

          for lib in scigma/*.dylib; do
            install_name_tool -id "@loader_path/$(basename "$lib")" "$lib"
            install_name_tool -change "$(otool -L scigma/libscigma.dylib | grep $(basename "$lib") | awk '{print $1}')" \
            "@loader_path/$(basename "$lib")" scigma/libscigma.dylib || true
          done

  build-windows:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-cmake

    - name: Configure
      shell: msys2 {0}
      run: cmake -B build -S source -DCMAKE_BUILD_TYPE=Release

    - name: Build
      shell: msys2 {0}
      run: cmake --build build
      
    - name: Bundle Windows dependencies
      shell: msys2 {0}
      run: |
        cp build/yourmodule.dll scigma/

        objdump -p build/libscigma.dll \
        | grep "DLL Name" \
        | awk '{print $3}' \
        | grep -viE 'kernel32|user32|advapi32|msvcrt' \
        | xargs -I{} cp /mingw64/bin/{} scigma/
