name: Build

on:
  push:
    branches: [ gh-actions-builds ]

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fortran compiler, OpenGL/X dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran cmake libglu1-mesa-dev xorg-dev

      - name: Configure
        run: cmake -B build -S source -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build
        
  build-macos-intel:
    name: Build (macOS Intel)
    runs-on: macos-15-intel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install gfortran
          
      - name: Expose Homebrew Fortran compiler
        run: |
          echo "$(brew --prefix gcc)/bin" >> $GITHUB_PATH
          echo "FC=gfortran" >> $GITHUB_ENV

      - name: Configure
        run: cmake -B build -S source -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wno-error=poison-system-directories -Wno-covered-switch-default"

      - name: Build
        run: cmake --build build

  build-macos-arm:
    name: Build (macOS ARM)
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install gfortran
          
      - name: Expose Homebrew Fortran compiler
        run: |
          echo "$(brew --prefix gcc)/bin" >> $GITHUB_PATH
          echo "FC=gfortran" >> $GITHUB_ENV

      - name: Disable libpng NEON on ARM
        run: |
          echo "CFLAGS=-DPNG_ARM_NEON_OPT=0" >> $GITHUB_ENV
          echo "CPPFLAGS=-DPNG_ARM_NEON_OPT=0" >> $GITHUB_ENV

      - name: Configure
        run: cmake -B build -S source -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wno-error=poison-system-directories -Wno-covered-switch-default"

      - name: Build
        run: cmake --build build

  build-windows:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-cmake

    - name: Configure
      shell: msys2 {0}
      run: cmake -B build -S source -DCMAKE_BUILD_TYPE=Release

    - name: Build
      shell: msys2 {0}
      run: cmake --build build



